### ISSUE TITLE
Missing word: commentor

### ISSUE THREAD

**Issue by cheesecracker** [flodolo/dictionary-en-us#3]
Hello,

The word "commentor(s)" is missing in the dictionary:
https://www.merriam-webster.com/dictionary/commenter
https://www.collinsdictionary.com/dictionary/english/commentor

Thank you and cheer

**Comment by flodolo** [comment]
Issues shouldn't be used to report missing terms. Please see instructions here
https://github.com/flodolo/dictionary-en-us#adding-new-terms

**Comment by cheesecracker** [comment]
May I suggest you to add a direct link in this page at "More information" section:
https://addons.mozilla.org/en-GB/firefox/addon/english-us-dictionary/

When I open the "support" page, the "Addig new terms" sentence was off my screen (because reading on a laptop with limited vertical pixels and 150% scaling...) and I already tried to click on several tabs to try to understand what I was supposed to do in that page....

**Comment by flodolo** [comment]
Sure, I can do that.

**Comment by cheesecracker** [comment]
Thanks 👍

**Comment by flodolo** [comment]
Unfortunately it doesn't look like it's possible 😞 

AMO only has one link field for `Homepage`, which is reused as `Support site` if you don't provide an email.

At this point, it might make sense to disable issues in this project.

**Comment by cheesecracker** [comment]
I see.  No problem.  Thanks 🙏
