### ISSUE TITLE
Add-on description page improvements?  (use after install, and more why better)

### ISSUE THREAD

**Issue by OneOfMany07** [flodolo/dictionary-en-us#5]
I'm trying to improve the built in dictionary/spellchecker, and their website recommended your add-on for my locale.  When I looked at the reviews page I noticed...

Rated 1 out of 5 by MartyGreg, [6 months ago] (https://addons.mozilla.org/en-US/firefox/addon/english-us-dictionary/reviews/2025250/)
"I wish users were writing why they give 5 stars. I installed it and it is nowhere to be found, not in the list nor on the toolbar. Obviously, it is installed somewhere, because when I click the add-on, (perhaps I did not really installed it), its only option is to 'remove' it"

And I agree more details about use after install could help a novice like myself.  I believe these are used separately from add-ons (from my other searches), but I can understand how users new to dictionaries in Firefox might just give up after not seeing it in the regular area (since it's listed on the addons website).

And if you're considering updating that page I was hoping for more description of why to use this than "adds 6000 words".  Meaning which words and why?  It might let users compare yours with another later... using a process other than comparing the words contained in each, or by size of addon.

Some people talk about SCOWL amounts, but I haven't read a description that explains it yet.  Just that higher includes more words, and the list of possible words sounds old (a list of web sites saved off by Google from 1998-2008?).  Meaning if that's the technical difference, list it...  but also maybe describe what it's doing or why yours is better in more general terms.

Just my 2 cents worth (and that other person's).  Either way, thanks for sharing your work with us all.

**Comment by flodolo** [comment]
Hi, first of all, thanks for taking the time to file the issue.

> I'm trying to improve the built in dictionary/spellchecker, and their website recommended your add-on for my locale.

Out of curiosity, could you link to the website in question?

This is just a repackage of the dictionary included in Firefox en-US builds, to allow users to install it as a stand-alone add-on, there is no plan to include additional features (which is actually not possible for dictionaries).

> And I agree more details about use after install could help a novice like myself. I believe these are used separately from add-ons (from my other searches), but I can understand how users new to dictionaries in Firefox might just give up after not seeing it in the regular area (since it's listed on the addons website).

This is valid, but it's related to the discoverability of the spellchecking feature in Firefox, not to a specific dictionary.
A good place to report this as an improvement is https://connect.mozilla.org/ 

> And if you're considering updating that page I was hoping for more description of why to use this than "adds 6000 words". Meaning which words and why? It might let users compare yours with another later... using a process other than comparing the words contained in each, or by size of addon.

I've added links to the list of words added by Mozilla and SCOWL's README. An explanation on [how those dictionaries are built](http://wordlist.aspell.net/scowl-readme/) really doesn't fit into an add-on description. I've also added a link to the [support page](https://support.mozilla.org/kb/how-do-i-use-firefox-spell-checker) explaining how spellchecking works.

**Comment by OneOfMany07** [comment]
https://addons.mozilla.org/en-US/firefox/language-tools/

Think that was a Google result for me, or a link from an answer I'd read through (I forget).  It lists 4 choices, and yours was the bottom one.  Believe the top was the old default, and one of the others is the current default (there after install for me).

And yeah, I finally found the SCOWL description and realized it was just a number they decided to invent (or didn't explain clearly).  That higher meant to include less used words.  Or maybe 'more obscure' is the measure.

Thanks for reading through my comments and responding so quickly!
